[alias]
xtask = "run -p xtask --"
build-example = "xtask build-example"
build-plugin = "xtask build-plugin"
build-plugins = "xtask build-plugins"
build-all = "xtask build-all"
list-plugins = "xtask list-plugins"

# Short
be = "build-example"
bp = "build-plugin"
bps = "build-plugins"
ba = "build-all"
lp = "list-plugins"
